### ISSUE TITLE
/var/run/docker.sock = localhost assumption is incorrect

### ISSUE THREAD

**Issue by kdubb** [chrisgahlert/gradle-dcompose-plugin#15]
Currently you are assuming that when the `DOCKER_HOST` is `/var/run/docker.sock` it means that all ports are exposed on `localhost`; this is incorrect. 

When mounting  `/var/run/docker.sock` into a docker container to allow the container to use the host's docker engine (aka Docker outside of Docker [DooD]) the host address of the exposed port becomes important.  This scenario is used in CI quite a bit.

My current workaround is to use Docker in Docker (aka DinD) just for the `integrationTest` phase of our gradle build. This has drawbacks because DinD uses it's own layer cache inside the container; meaning it must re-pull all of our images for each integrationTest run.

I'm assuming just parsing the port information just as you do for `DOCKER_HOST=tcp://blah:2375` would fix the issue (but I'm not quite sure).

**Comment by chrisgahlert** [comment]
Hi,

the code in question can be found [here](https://github.com/chrisgahlert/gradle-dcompose-plugin/blob/0d655badbec2fc9ba21be3180cca27bbd72dc9e1/src/main/groovy/com/chrisgahlert/gradledcomposeplugin/extension/DefaultService.groovy#L272).

I'm currently not processing the port information of the host port bindings, as these would always return the IP `0.0.0.0` in the default configuration. In case you are using a Docker Swarm, the Port's host address should be correctly populated. (You can verify this by running e.g. `docker port my-container 8080` - this will most likely return something like `0.0.0.0:32017/tcp`.) 
For that reason, I cannot find out the actual IP/host address to use (unless you correctly populated the advertise address in your Docker daemon).

The easy solution for your problem would be to set the `DOCKER_HOST` variable to something like `tcp://blah:2375`. In that case the host will be assumed to be `blah`.

Another workaround would be:

```gradle
integrationTest {
    dependsOn startDbContainer
    finalizedBy removeDbContainer

    doFirst {
        systemProperty 'db.host', (project.hasProperty('dockerHostAddress') ? dockerHostAddress : dcompose.db.dockerHost)
        systemProperty 'db.port', dcompose.db.findHostPort(3306)
    }
    doLast {
        systemProperties.remove 'db.host'
        systemProperties.remove 'db.port'
    }
}
```

Then you could launch the build e.g. with `./gradlew integrationTest -PdockerHostAddress=10.0.0.2`.

If you feel like this is a hack, I could make the dockerHost configurable, e.g. by something like this:
```gradle
dcompose {
  externalHostAddress = 'blah'
}
```

Kind regards

**Comment by kdubb** [comment]
When running _inside_ docker and wanting to use the outside docker engine one generally cannot set the `DOCKER_HOST` without resorting to DinD. In many cases a TCP host engine is not easily possible (e.g. macOS and Kubernetes are restricted to unix without hacks).

When running in DooD the unix socket is mounted into the container as a volume. Normal docker commands work fine in this case; they are able to work out that the IP address that ports are exposed on the external interface not the container's localhost.   It seems the plugin _should_ would like the docker commands (since they use the same API interface), no?

**Comment by chrisgahlert** [comment]
From what I understand, it is as follows:

`host-buildslave` is running a Docker Daemon.

If you now launch a container, that runs your build you can give it access to the buildslave's Docker Daemon:

```shell
host-buildslave> docker run \
                            --rm \
                            -h host-buildcontainer \
                            -v $(pwd):/work my-gradle-image \
                            -v /var/run/docker.sock:/var/run/docker.sock \
                            my-build-image:latest \
                            /work/gradlew integrationTest
```

If the build now talks to the Docker Host, it doesn't know that the actual Daemon is not inside the `host-buildcontainer`. The build will start containers talking to the Daemon with HTTP REST written to the socket. If you do it manually, it would be something like:

```shell
host-buildcontainer> docker run \
                                -d \
                                --name webserver \
                                -p 80 \
                                -v /work/build/html:/var/nginx/html \
                                nginx:latest
```

If you now try to figure out, which host/port to use, Docker doesn't give you the correct information:

```shell
host-buildcontainer> docker port webserver 80
0.0.0.0:32022/tcp
```

That is because in the default configuration, the Docker daemon of the Build slave, doesn't know, which external IP to advertise - as it might have multiple IP addresses and it can't guess which route the caller of the Docker API will be taking. (This can be configured through the advertise address of the Daemon. It HAS to be correctly configured if you use Docker Swarm. I'm currently not sure if you can still configure it, if you are not using Swarm.)

If the `docker port` command returns an IP address in your case: I'll try to implement the feature to parse this information and populate it correctly in the next couple of days.

If the `docker port` command DOES NOT return an actual IP address: You can make use of one of the workarounds I described in my last comment.

I hope that this clarifies this a bit! :)

Kind regards

**Comment by jimmypoms** [comment]
We had the same issue in our environment. We got around it by using docker host network (https://docs.docker.com/network/host/).

I hope this works for you ;)

**Comment by chrisgahlert** [comment]
Closing it for now... Please comment, if it is not fixed for you!
