### ISSUE TITLE
Start Container never ends

### ISSUE THREAD

**Issue by jorge-pascual** [chrisgahlert/gradle-dcompose-plugin#31]
Hi! Congrats for this amazing plugin!

I'm trying to use it but I'm in troubles with the starting task. All works fine, but when I launch the startXXXXContainer and I have "waitForCommand=true" the task never ends. Is anyone experimenting the same thing ? any clue? 

Thank you!

**Comment by chrisgahlert** [comment]
Hi Jorge,

thanks for your feedback.

When launching a container with `waitForCommand=true`, this basically means: Wait for the container to exit with a zero return code.

The correct use case for the `waitForCommand=true` is e.g. a container, that produces some output and then exits.

So if your container is a server (e.g. nginx, apache, mysql, ...), the container will never exit on it's own, as it still running and waiting for connections. In this case, what you are looking for is most likely:
1. Using `waitForCommand=false`: This will start the container, when you run `startXXXContainer`, but the Gradle task will continue right after starting it.
2. Using something like `waitForHealthcheck=true` when you want to wait for your container 'to be ready'. In the case of a server this could mean 'ready to accept connections'. 

I hope this clears things up! :)

Kind regards, 
Chris

**Comment by chrisgahlert** [comment]
P.S. You'll find a list of available options and their usage here: https://github.com/chrisgahlert/gradle-dcompose-plugin/wiki/02.-List-of-service-properties#runtime-container-properties

**Comment by jorge-pascual** [comment]
Thank you so much Chris!. I misunderstood the behaviour.

**Comment by ohquero** [comment]
Hi, I'm having some problem when using this plugin with containers that needs some time to boot up because the application runt by Gradle is executed before containers completely boot up. I think this happens because after the bootup the container needs to execute a script to be fully initialized.

I've tried to make use of the Dockers healthcheck functionality and the `waitForHealthCheck` property, but since the first healthcheck is executed after `--interval` time (as stated in the [documentation](https://docs.docker.com/engine/reference/builder/#healthcheck)) I must keep the interval as low as the time needed by the container to be fully initialized, with the side effect that the healthcheck is executed very frequently, which is a bit annoying.

I think a better solution could be the use of a event thrown by the container that notifies Gradle notifying that the bootup is done, but I don't know if it is something achievable because I'm quite new to both tools. What do you think about?

Anyway thank you for your work, is really useful and simple to use.
