### ISSUE TITLE
Old volumes are reused

### ISSUE THREAD

**Issue by henrik242** [chrisgahlert/gradle-dcompose-plugin#32]
@chrisgahlert Is there a way to ensure that old volumes are *not* reused?  I have tried setting the following without success:

```
preserveVolumes = false
forceRemoveImage = true
```

**Comment by chrisgahlert** [comment]
Hi,

the flag `preserveVolumes` tells the plugin, whether the volumes should be removed or preserved, when the container itself is removed - i.e. calling the `removeMyServiceContainer` task.

The flag `forceRemoveImage` tells the plugin, whether the intermediate images (when building an image) should be removed, when calling the `buildMyServiceImage`.

In order to solve your problem, you need to make sure, that the flag `preserveVolumes` is set to `false` AND that you call the `removeMyServiceContainer` task. It depends on your use case, but generally, this can be accomplished via task dependencies:
```gradle
dcompose {
  sample1 {
    image = ...
    preserveVolumes = false
  }
  sample2 {
    image = ...
    preserveVolumes = false
  }
}

// The following makes sure, the container is re-created every time it is needed:
createSample1Container.outputs.upToDateWhen { false } 

test {
  // This makes sure, the container is launched before the test task
  dependsOn dcompose.sample2

  // This makes sure, the container is removed after running the test task (even if it failed):
  finalizedBy removeSample2Container
}
```

I hope this clears things up? :)

Kind regards

**Comment by chrisgahlert** [comment]
P.S.
I just remembered that `preserveVolumes` is `false` by default. Therefore you could omit that as well. For an example, look at the `mongoTest` container in the sample project:
https://github.com/chrisgahlert/gradle-dcompose-sample/blob/314bd52af6c80d1098865ca612ab9ed68526c62c/build.gradle#L42

**Comment by henrik242** [comment]
Thank you! This was all that I needed using kotlin-dsl:
```
            val createPostgresContainer by tasks.getting {
                // Makes sure volumes are recreated, i.e. not using data from earlier runs
                outputs.upToDateWhen { false }
            }
```
